"""Agent: scan imports, pick third-party deps, resolve conflicts via LLM, emit setup.py."""

from __future__ import annotations

import ast
import json
import logging
import os
import re
import subprocess
from pathlib import Path
import tempfile
import time
import venv
from typing import Any, Dict, Iterable, List, Mapping, Optional, Sequence, Set, Tuple

from agents.infra.llm_client import LLMClient

from .pip_import_heuristic import (
    ast_top_level_import_roots,
    filter_third_party_import_roots,
    stdlib_names,
    third_party_roots_to_heuristic_rows,
)

_LOGGER = logging.getLogger(__name__)


def _iter_python_files(root: Path, skip_dirs: Set[str]) -> Iterable[Path]:
    if not root.is_dir():
        return
    for path in root.rglob("*.py"):
        parts = set(path.relative_to(root).parts[:-1])
        if parts & skip_dirs:
            continue
        if path.name == "conftest.py" or path.name.startswith("test_"):
            continue
        yield path


def _discover_local_top_level(root: Path) -> Set[str]:
    """First-party top-level names: immediate packages/modules under root."""
    local: Set[str] = set()
    if not root.is_dir():
        return local
    for child in root.iterdir():
        name = child.name
        if name.startswith(".") or name == "__pycache__":
            continue
        if child.is_dir():
            if (child / "__init__.py").is_file():
                local.add(name)
        elif child.suffix == ".py":
            stem = child.stem
            if stem and stem != "setup":
                local.add(stem)
    return local


def _collect_imports_across_tree(
    root: Path,
    skip_dir_names: Optional[Set[str]] = None,
) -> Dict[str, Any]:
    skip = set(skip_dir_names or (".git", ".hg", ".tox", ".venv", "venv", "__pycache__", ".mypy_cache"))
    by_file: Dict[str, List[str]] = {}
    all_roots: Set[str] = set()
    errors: List[Dict[str, str]] = []

    for path in sorted(_iter_python_files(root, skip)):
        rel = str(path.relative_to(root))
        try:
            source = path.read_text(encoding="utf-8", errors="replace")
        except OSError as exc:
            errors.append({"file": rel, "error": str(exc)})
            continue
        try:
            tree = ast.parse(source, filename=str(path))
        except SyntaxError as exc:
            errors.append({"file": rel, "error": f"SyntaxError: {exc}"})
            continue
        tops = ast_top_level_import_roots(tree)
        if tops:
            by_file[rel] = sorted(tops)
            all_roots.update(tops)

    return {
        "imports_by_file": by_file,
        "all_import_roots": sorted(all_roots),
        "parse_errors": errors,
    }


def _detect_spec_conflicts(rows: Sequence[Mapping[str, str]]) -> List[Dict[str, Any]]:
    """Heuristic conflicts: same distribution suggested from different import roots, etc."""
    by_dist: Dict[str, List[str]] = {}
    for row in rows:
        dist = (row.get("suggested_distribution") or "").strip()
        root = (row.get("import_root") or "").strip()
        if not dist or not root:
            continue
        by_dist.setdefault(dist, []).append(root)

    conflicts: List[Dict[str, Any]] = []
    for dist, roots in by_dist.items():
        unique_roots = sorted(set(roots))
        if len(unique_roots) > 1:
            conflicts.append(
                {
                    "kind": "multiple_import_roots_same_distribution",
                    "distribution": dist,
                    "import_roots": unique_roots,
                }
            )

    # Duplicate distribution rows (identical) are not conflicts
    return conflicts


def _render_setup_py(
    package_name: str,
    version: str,
    install_requires: Sequence[str],
    python_requires: str,
) -> str:
    req_lines = ",\n        ".join(repr(s) for s in install_requires)
    return (
        "# Generated by Repo0 SetupPyAgent — edit as needed.\n"
        "from setuptools import find_packages, setup\n\n"
        f'setup(\n'
        f'    name="{_escape_setup_str(package_name)}",\n'
        f'    version="{_escape_setup_str(version)}",\n'
        f"    packages=find_packages(exclude=[\"tests\", \"tests.*\", \"test\", \"test.*\"]),\n"
        f'    python_requires="{_escape_setup_str(python_requires)}",\n'
        f"    install_requires=[\n        {req_lines}\n    ],\n"
        f")\n"
    )


def _escape_setup_str(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _normalize_install_list(raw: Any) -> List[str]:
    if not isinstance(raw, list):
        return []
    out: List[str] = []
    for item in raw:
        if isinstance(item, str) and item.strip():
            out.append(item.strip())
    return out


def _sanitize_runtime_requirements(
    install_requires: Sequence[str],
    *,
    package_name: str,
    local_top_level: Set[str],
) -> List[str]:
    blocked = {
        "pytest",
        "_pytest",
        "py.test",
        "src",
        "tests",
        "test",
        "conftest",
    }
    pkg_norm = re.sub(r"[-.]+", "_", str(package_name or "").strip().lower())
    local_norm = {re.sub(r"[-.]+", "_", item.strip().lower()) for item in local_top_level if str(item).strip()}
    cleaned: List[str] = []
    seen: Set[str] = set()
    for req in install_requires:
        if not isinstance(req, str) or not req.strip():
            continue
        item = req.strip()
        dist = _split_dist_name_from_requirement(item)
        norm = re.sub(r"[-.]+", "_", dist.strip().lower())
        if norm in blocked:
            continue
        if pkg_norm and norm == pkg_norm:
            continue
        if norm in local_norm:
            continue
        if item not in seen:
            seen.add(item)
            cleaned.append(item)
    return cleaned


def _split_dist_name_from_requirement(requirement: str) -> str:
    """Best-effort: 'distname[extra]>=1.2' -> 'distname'."""
    match = re.match(r"^\s*([A-Za-z0-9][A-Za-z0-9_.-]*)\s*", requirement or "")
    if not match:
        return requirement.strip()
    return match.group(1)


def _check_setup_py_compiles(setup_py_path: Path) -> Dict[str, Any]:
    import py_compile

    try:
        py_compile.compile(str(setup_py_path), doraise=True)
        return {"ok": True, "error": ""}
    except Exception as exc:
        return {"ok": False, "error": f"{type(exc).__name__}: {exc}"}


def _run_cmd(cmd: List[str], timeout_seconds: float) -> Dict[str, Any]:
    try:
        proc = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout_seconds,
            check=False,
        )
        return {
            "ok": proc.returncode == 0,
            "returncode": proc.returncode,
            "stdout": proc.stdout[-20000:] if proc.stdout else "",
            "stderr": proc.stderr[-20000:] if proc.stderr else "",
        }
    except subprocess.TimeoutExpired as exc:
        return {
            "ok": False,
            "returncode": -1,
            "stdout": (exc.stdout[-20000:] if exc.stdout else ""),
            "stderr": f"TimeoutExpired after {timeout_seconds}s: {exc}",
        }
    except Exception as exc:
        return {
            "ok": False,
            "returncode": -1,
            "stdout": "",
            "stderr": f"{type(exc).__name__}: {exc}",
        }


def _venv_python_exe(venv_dir: Path) -> Path:
    # Unix-only project environment (Linux).
    return venv_dir / "bin" / "python"


def _postcheck_install_and_imports(
    *,
    venv_dir: Path,
    requirements: Sequence[str],
    import_roots: Sequence[str],
    pip_install_timeout_seconds: float,
    max_import_roots: int,
) -> Dict[str, Any]:
    # Ensure venv exists.
    if venv_dir.exists():
        try:
            for p in venv_dir.iterdir():
                # Avoid deleting the venv python entirely; simplest is just reuse.
                # If the venv is corrupted, pip install will fail and the caller can retry.
                _ = p
        except Exception:
            pass
    else:
        builder = venv.EnvBuilder(with_pip=True, clear=False, symlinks=False, upgrade=False)
        builder.create(str(venv_dir))

    python_exe = _venv_python_exe(venv_dir)
    if not python_exe.exists():
        return {"ok": False, "error": f"venv python not found: {python_exe}"}

    req_file = venv_dir / "requirements.txt"
    req_lines = [r for r in requirements if isinstance(r, str) and r.strip()]
    req_file.write_text("\n".join(req_lines) + ("\n" if req_lines else ""), encoding="utf-8")

    dist_names = sorted(
        {
            _split_dist_name_from_requirement(r)
            for r in req_lines
            if isinstance(r, str) and r.strip()
        }
    )

    pip_cmd = [
        str(python_exe),
        "-m",
        "pip",
        "install",
        "--disable-pip-version-check",
        "--no-input",
        "-r",
        str(req_file),
    ]
    pip_result = _run_cmd(pip_cmd, timeout_seconds=pip_install_timeout_seconds)

    if not pip_result["ok"]:
        return {
            "ok": False,
            "pip_install_ok": False,
            "pip_install_stdout": pip_result.get("stdout", ""),
            "pip_install_stderr": pip_result.get("stderr", ""),
            "missing_import_roots": [],
        }

    # Collect versions from the isolated venv without importing modules.
    version_check_code = (
        "import importlib.metadata as m, json; "
        f"dist_names={json.dumps(dist_names)}; "
        "out={}; missing=[]; "
        "for d in dist_names: "
        "    try: out[d]=m.version(d) "
        "    except Exception: missing.append(d) "
        "print(json.dumps({'installed_versions': out, 'missing': missing}))"
    )
    version_cmd = [str(python_exe), "-c", version_check_code]
    version_result = _run_cmd(version_cmd, timeout_seconds=600.0)
    installed_versions: Dict[str, str] = {}
    versions_missing: List[str] = []
    if version_result["ok"]:
        try:
            parsed_versions = json.loads((version_result.get("stdout") or "").strip() or "{}")
            installed_versions = parsed_versions.get("installed_versions", {}) if isinstance(parsed_versions, dict) else {}
            versions_missing = parsed_versions.get("missing", []) if isinstance(parsed_versions, dict) else []
        except Exception:
            installed_versions = {}
            versions_missing = []

    # Only check presence; avoid importing modules with side-effects.
    checked_import_roots = sorted(set([r for r in import_roots if r]))[: max(0, int(max_import_roots))]
    import_check_code = (
        "import importlib.util, json; "
        f"roots={json.dumps(checked_import_roots)}; "
        "missing=[r for r in roots if importlib.util.find_spec(r) is None]; "
        "print(json.dumps({'checked': roots, 'missing': missing}))"
    )
    import_cmd = [str(python_exe), "-c", import_check_code]
    import_result = _run_cmd(import_cmd, timeout_seconds=600.0)
    if not import_result["ok"]:
        return {
            "ok": False,
            "pip_install_ok": True,
            "pip_install_stdout": pip_result.get("stdout", ""),
            "pip_install_stderr": pip_result.get("stderr", ""),
            "missing_import_roots": [],
            "import_check_stderr": import_result.get("stderr", ""),
        }

    parsed: Dict[str, Any] = {}
    try:
        parsed = json.loads(import_result.get("stdout", "").strip() or "{}")
    except Exception:
        parsed = {"checked": checked_import_roots, "missing": []}

    return {
        "ok": True,
        "pip_install_ok": True,
        "pip_install_stdout": pip_result.get("stdout", ""),
        "pip_install_stderr": pip_result.get("stderr", ""),
        "missing_import_roots": parsed.get("missing", []),
        "checked_import_roots": parsed.get("checked", checked_import_roots),
        "installed_versions": installed_versions,
        "versions_missing": versions_missing,
    }


def _pin_install_requires_by_versions(
    install_requires: Sequence[str],
    installed_versions: Mapping[str, str],
) -> List[str]:
    # Match using normalized keys to handle distribution-name casing differences.
    norm_installed = {str(k).lower(): str(v) for k, v in (installed_versions or {}).items()}
    pinned: List[str] = []

    for req in install_requires:
        if not isinstance(req, str) or not req.strip():
            continue
        dist = _split_dist_name_from_requirement(req)
        norm_dist = str(dist).lower()
        version = norm_installed.get(norm_dist)
        if not version:
            pinned.append(req.strip())
            continue

        # If req already has a spec, we overwrite to an exact pin for reproducibility.
        pinned.append(f"{dist}=={version}")

    return pinned


class SetupPyAgent:
    """Collect imports from a tree, isolate third-party deps, optionally use LLM, write setup.py."""

    def __init__(self, api_config: Optional[Dict[str, Any]] = None, output_dir: str = ".") -> None:
        self.api_config = api_config or {}
        self.output_dir = output_dir
        self.llm_client: Optional[LLMClient] = None
        if self.api_config.get("api_key"):
            self.llm_client = LLMClient(self.api_config, output_dir, agent_name="setup_py_agent")

    def run(
        self,
        project_root: str | Path,
        setup_py_path: Optional[str | Path] = None,
        package_name: Optional[str] = None,
        version: str = "0.1.0",
        python_requires: str = ">=3.10",
        local_top_level: Optional[Set[str] | Sequence[str]] = None,
        skip_llm: bool = False,
        skip_scan_dir_names: Optional[Set[str]] = None,
        enable_postcheck: bool = True,
        postcheck_pip_install_timeout_seconds: float = 600.0,
        postcheck_max_import_roots: int = 30,
        postcheck_max_total_requirements: int = 60,
        strict_imports: bool = True,
    ) -> Dict[str, Any]:
        """
        Scan ``project_root`` for ``import`` / ``from … import``, drop stdlib and local packages,
        then write ``setup.py`` with ``install_requires``. Optional LLM merges pins and resolves
        ambiguous / conflicting mappings.
        """
        root = Path(project_root).resolve()
        out_path = Path(setup_py_path).resolve() if setup_py_path else (root / "setup.py")

        default_skip_dirs = {
            ".git", ".hg", ".tox", ".venv", "venv", "__pycache__", ".mypy_cache",
            "tests", "test", "testing",
        }
        scan = _collect_imports_across_tree(root, set(skip_scan_dir_names or set()) | default_skip_dirs)
        discovered_local = _discover_local_top_level(root)
        if local_top_level is not None:
            effective_local = set(local_top_level) | discovered_local | {root.name}
        else:
            effective_local = discovered_local | {root.name}

        stdlib = stdlib_names()
        third_party, skipped = filter_third_party_import_roots(
            scan["all_import_roots"],
            local_top_level=effective_local,
            stdlib=stdlib,
        )
        heuristic_rows = third_party_roots_to_heuristic_rows(third_party)
        conflicts = _detect_spec_conflicts(heuristic_rows)

        install_requires = sorted(
            {
                (
                    f"{r['suggested_distribution']}{r['version_spec']}"
                    if r["version_spec"]
                    else r["suggested_distribution"]
                )
                for r in heuristic_rows
            }
        )
        install_requires = _sanitize_runtime_requirements(
            install_requires,
            package_name=package_name or root.name,
            local_top_level=effective_local,
        )
        baseline_install_requires = sorted(set(install_requires))
        llm_notes = ""
        conflict_resolutions: List[Dict[str, str]] = []
        llm_mapping_changes: List[Dict[str, str]] = []
        llm_dropped_import_roots: List[Dict[str, str]] = []
        llm_applied = False

        use_llm = bool(self.llm_client) and not skip_llm and (third_party or conflicts)
        if use_llm and self.llm_client:
            try:
                payload = {
                    "heuristic_rows": heuristic_rows,
                    "detected_conflicts": conflicts,
                    "third_party_import_roots": third_party,
                    "skipped_import_roots": skipped,
                    "project_root": str(root),
                    "local_top_level": sorted(effective_local),
                    "task": (
                        "Produce install_requires for setuptools. Resolve namespace / duplicate "
                        "distribution issues. Prefer PEP 508. Omit stdlib and local. "
                        "Use single constraint per distribution."
                    ),
                }
                prompt = (
                    "You finalize setup.py dependencies for a Python project.\n"
                    "Input is JSON with heuristic import_root -> PyPI guesses and detected conflicts.\n"
                    "Return ONLY valid JSON with schema:\n"
                    "{\n"
                    '  "install_requires": ["dist", "other>=1.2"],\n'
                    '  "mapping_changes": [\n'
                    '    {"import_root": "...", "chosen_distribution": "...", "reason": "..."}\n'
                    "  ],\n"
                    '  "dropped_import_roots": [{"import_root": "...", "reason": "..."}],\n'
                    '  "conflict_resolutions": [{"issue": "...", "resolution": "..."}],\n'
                    '  "notes": "short"\n'
                    "}\n"
                    "Rules:\n"
                    "- One entry per PyPI distribution; merge duplicates.\n"
                    "- If unsure about version, omit version constraint.\n"
                    "- Strict mode: do NOT drop any dependency that corresponds to an input third_party_import_root.\n"
                    "- The codebase already filtered out stdlib and local packages. Keep one dependency per provided import_root mapping.\n"
                    "- You may correct import_root -> distribution mapping when the heuristic guess is likely wrong, but keep the dependency coverage.\n\n"
                    "Quality bar:\n"
                    "- Prefer well-known PyPI names.\n"
                    "- If multiple distributions seem plausible, pick the most likely runtime dependency.\n\n"
                    f"INPUT:\n{json.dumps(payload, indent=2, ensure_ascii=True)}"
                )
                llm_max_retry_times = max(
                    1,
                    int(self.api_config.get("setup_py_llm_max_retry_times", 3)),
                )
                response = self.llm_client.call_json(
                    [
                        {
                            "role": "system",
                            "content": "You are a Python packaging expert. Return only valid JSON.",
                        },
                        {"role": "user", "content": prompt},
                    ],
                    temperature=0.0,
                    max_retry_times=llm_max_retry_times,
                )
                if isinstance(response, dict):
                    llm_applied = True
                    merged = _normalize_install_list(response.get("install_requires"))
                    if merged:
                        install_requires = _sanitize_runtime_requirements(
                            merged,
                            package_name=package_name or root.name,
                            local_top_level=effective_local,
                        )
                    cr = response.get("conflict_resolutions")
                    if isinstance(cr, list):
                        for item in cr:
                            if isinstance(item, dict) and item.get("issue") and item.get("resolution"):
                                conflict_resolutions.append(
                                    {"issue": str(item["issue"]), "resolution": str(item["resolution"])}
                                )
                    mapping_changes = response.get("mapping_changes")
                    if isinstance(mapping_changes, list):
                        for item in mapping_changes:
                            if (
                                isinstance(item, dict)
                                and item.get("import_root")
                                and item.get("chosen_distribution")
                                and item.get("reason")
                            ):
                                llm_mapping_changes.append(
                                    {
                                        "import_root": str(item["import_root"]),
                                        "chosen_distribution": str(item["chosen_distribution"]),
                                        "reason": str(item["reason"]),
                                    }
                                )
                    dropped = response.get("dropped_import_roots")
                    if isinstance(dropped, list):
                        for item in dropped:
                            if isinstance(item, dict) and item.get("import_root") and item.get("reason"):
                                llm_dropped_import_roots.append(
                                    {"import_root": str(item["import_root"]), "reason": str(item["reason"])}
                                )
                    notes_val = response.get("notes")
                    if isinstance(notes_val, str):
                        llm_notes = notes_val.strip()

                    # Enforce strict coverage: never drop baseline deps in strict_imports mode.
                    if strict_imports:
                        install_requires = _sanitize_runtime_requirements(
                            sorted(set(baseline_install_requires) | set(install_requires or [])),
                            package_name=package_name or root.name,
                            local_top_level=effective_local,
                        )
            except Exception as exc:
                _LOGGER.warning("SetupPyAgent LLM resolution failed, keeping heuristic list: %s", exc)

        inferred_name = package_name
        if not inferred_name:
            if len(effective_local) == 1:
                inferred_name = next(iter(effective_local))
            else:
                inferred_name = root.name.replace("-", "_")
                _LOGGER.info(
                    "SetupPyAgent: ambiguous package name; using directory name %r", inferred_name
                )

        install_requires = _sanitize_runtime_requirements(
            install_requires,
            package_name=package_name or root.name,
            local_top_level=effective_local,
        )
        setup_body = _render_setup_py(
            package_name=inferred_name,
            version=version,
            install_requires=install_requires,
            python_requires=python_requires,
        )
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(setup_body, encoding="utf-8")

        postcheck_report: Dict[str, Any] = {}
        llm_postcheck_used = False
        if enable_postcheck and install_requires and third_party:
            postcheck_report["setup_py_compile"] = _check_setup_py_compiles(out_path)
            if len(install_requires) > int(postcheck_max_total_requirements):
                postcheck_report["skipped"] = True
                postcheck_report["skip_reason"] = (
                    f"Too many requirements for venv postcheck: "
                    f"{len(install_requires)} > {int(postcheck_max_total_requirements)}"
                )
            else:
                postcheck_start = time.time()
                Path(self.output_dir).mkdir(parents=True, exist_ok=True)
                venv_dir = Path(
                    tempfile.mkdtemp(
                        prefix="repo0_setup_postcheck_",
                        dir=str(self.output_dir),
                    )
                )
                try:
                    # Phase 1: validate install_requires via isolated venv.
                    postcheck_report.update(
                        _postcheck_install_and_imports(
                            venv_dir=venv_dir,
                            requirements=install_requires,
                            import_roots=third_party,
                            pip_install_timeout_seconds=float(postcheck_pip_install_timeout_seconds),
                            max_import_roots=int(postcheck_max_import_roots),
                        )
                    )

                    postcheck_report["duration_seconds"] = round(time.time() - postcheck_start, 3)

                    # Phase 2 (optional): LLM tries to correct mapping if venv install/import indicates likely issues.
                    postcheck_failed_install = not bool(postcheck_report.get("pip_install_ok", False))
                    missing_import_roots = postcheck_report.get("missing_import_roots", []) or []
                    postcheck_failed_imports = bool(missing_import_roots)

                    if (
                        self.llm_client
                        and not skip_llm
                        and (postcheck_failed_install or postcheck_failed_imports)
                    ):
                        try:
                            llm_postcheck_used = True
                            postcheck_failed_install_stderr = postcheck_report.get("pip_install_stderr", "") or ""
                            postcheck_missing = list(missing_import_roots)[
                                : int(postcheck_max_import_roots)
                            ]

                            postcheck_payload = {
                                "install_requires": install_requires,
                                "third_party_import_roots": third_party[
                                    : int(postcheck_max_import_roots)
                                ],
                                "missing_import_roots": postcheck_missing,
                                "pip_install_stderr": postcheck_failed_install_stderr[-40000:],
                                "detected_conflicts": conflicts,
                                "heuristic_dependency_rows": heuristic_rows,
                            }
                            postcheck_prompt = (
                                "You are a Python packaging expert. Postcheck indicates that some dependencies are incorrect.\n"
                                "Given JSON input, fix install_requires so that importing third_party_import_roots becomes possible.\n"
                                "Return ONLY valid JSON with schema:\n"
                                "{\n"
                                '  "install_requires": ["dist", "other>=1.2"],\n'
                                '  "mapping_changes": [{"import_root":"...","chosen_distribution":"...","reason":"..."}],\n'
                                '  "notes": "short"\n'
                                "}\n"
                                "Rules:\n"
                                "- Deduplicate by distribution name.\n"
                                "- If pip couldn't find a distribution, replace it with the likely correct PyPI package.\n"
                                "- Prefer PEP 508 requirements without extras unless clearly required.\n"
                            )
                            response2 = self.llm_client.call_json(
                                [
                                    {"role": "system", "content": "Return only valid JSON."},
                                    {
                                        "role": "user",
                                        "content": postcheck_prompt
                                        + "\nINPUT:\n"
                                        + json.dumps(
                                            postcheck_payload,
                                            indent=2,
                                            ensure_ascii=True,
                                        ),
                                    },
                                ],
                                temperature=0.0,
                                max_retry_times=max(
                                    1,
                                    int(
                                        self.api_config.get(
                                            "setup_py_postcheck_llm_max_retry_times",
                                            self.api_config.get("setup_py_llm_max_retry_times", 3),
                                        )
                                    ),
                                ),
                            )
                            if isinstance(response2, dict):
                                merged2 = _normalize_install_list(
                                    response2.get("install_requires")
                                )
                                if merged2:
                                    install_requires = _sanitize_runtime_requirements(
                                        merged2,
                                        package_name=package_name or root.name,
                                        local_top_level=effective_local,
                                    )
                                    install_requires = _sanitize_runtime_requirements(
                                        install_requires,
                                        package_name=package_name or root.name,
                                        local_top_level=effective_local,
                                    )
                                    setup_body = _render_setup_py(
                                        package_name=inferred_name,
                                        version=version,
                                        install_requires=install_requires,
                                        python_requires=python_requires,
                                    )
                                    out_path.write_text(setup_body, encoding="utf-8")
                                    # Re-run postcheck (fresh venv might be heavy; reuse existing venv for speed).
                                    postcheck_report.update(
                                        _postcheck_install_and_imports(
                                            venv_dir=venv_dir,
                                            requirements=install_requires,
                                            import_roots=third_party,
                                            pip_install_timeout_seconds=float(
                                                postcheck_pip_install_timeout_seconds
                                            ),
                                            max_import_roots=int(
                                                postcheck_max_import_roots
                                            ),
                                        )
                                    )
                                    postcheck_report["setup_py_compile"] = _check_setup_py_compiles(out_path)
                        except Exception as exc:
                            postcheck_report.setdefault(
                                "llm_postcheck_error",
                                f"{type(exc).__name__}: {exc}",
                            )
                except Exception as exc:
                    postcheck_report.setdefault("error", f"{type(exc).__name__}: {exc}")

        # If postcheck succeeded, pin versions to solve "no version constraint" issue.
        # This does not affect the already-installed venv; it only updates setup.py output.
        try:
            if postcheck_report.get("pip_install_ok") and postcheck_report.get("installed_versions"):
                pinned = _pin_install_requires_by_versions(
                    install_requires=install_requires,
                    installed_versions=postcheck_report.get("installed_versions", {}),
                )
                if pinned and pinned != list(install_requires):
                    install_requires = _sanitize_runtime_requirements(
                        pinned,
                        package_name=package_name or root.name,
                        local_top_level=effective_local,
                    )
                    install_requires = _sanitize_runtime_requirements(
                        install_requires,
                        package_name=package_name or root.name,
                        local_top_level=effective_local,
                    )
                    setup_body = _render_setup_py(
                        package_name=inferred_name,
                        version=version,
                        install_requires=install_requires,
                        python_requires=python_requires,
                    )
                    out_path.write_text(setup_body, encoding="utf-8")
                    postcheck_report["pinned_install_requires"] = install_requires
        except Exception as exc:
            postcheck_report.setdefault("version_pinning_error", f"{type(exc).__name__}: {exc}")

        install_requires = _sanitize_runtime_requirements(
            install_requires,
            package_name=package_name or root.name,
            local_top_level=effective_local,
        )
        final_setup_body = _render_setup_py(
            package_name=inferred_name,
            version=version,
            install_requires=install_requires,
            python_requires=python_requires,
        )
        if final_setup_body != setup_body:
            setup_body = final_setup_body
            out_path.write_text(setup_body, encoding="utf-8")

        return {
            "setup_py_path": str(out_path),
            "package_name": inferred_name,
            "local_top_level": sorted(effective_local),
            "third_party_import_roots": third_party,
            "skipped_import_roots": skipped,
            "imports_by_file": scan["imports_by_file"],
            "parse_errors": scan["parse_errors"],
            "heuristic_dependency_rows": heuristic_rows,
            "detected_conflicts": conflicts,
            "install_requires": install_requires,
            "llm_used": llm_applied,
            "conflict_resolutions": conflict_resolutions,
            "llm_notes": llm_notes,
            "llm_mapping_changes": llm_mapping_changes,
            "llm_dropped_import_roots": llm_dropped_import_roots,
            "postcheck_report": postcheck_report,
            "llm_postcheck_used": llm_postcheck_used,
        }
