#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import shlex
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run Repo0 incremental requirement iteration from a prepared manifest.")
    parser.add_argument("--manifest", type=Path, required=True, help="iteration_manifest.json generated by prepare_requirement_iteration.py")
    parser.add_argument("--base-url", type=str, required=True)
    parser.add_argument("--api-key", type=str, required=True)
    parser.add_argument("--reasoning-effort", type=str, default="", help="Optional reasoning_effort to pass through to the LLM API.")
    parser.add_argument("--model", type=str, default="gpt-5-mini")
    parser.add_argument("--max-workers", type=int, default=8)
    parser.add_argument("--run", action="store_true", help="Actually execute run_agents.py. Default: print command only.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    manifest = json.loads(args.manifest.read_text(encoding="utf-8"))
    target_repo_dir = Path(manifest["target_repo_dir"]).resolve()
    repo_name = target_repo_dir.name
    evolve_requirements_file = Path(manifest["evolve_requirements_file"]).resolve()
    requirements_file = target_repo_dir / "readme_output" / "requirements.json"
    output_dir = target_repo_dir / "agents_output"
    workspace = ROOT

    cmd = [
        sys.executable,
        str(ROOT / "run_agents.py"),
        "--workspace",
        str(workspace),
        "--repo",
        repo_name,
        "--requirements-file",
        str(requirements_file),
        "--evolve-requirements-file",
        str(evolve_requirements_file),
        "--output",
        str(output_dir),
        "--base-url",
        args.base_url,
        "--api-key",
        args.api_key,
        "--model",
        args.model,
        "--max-workers",
        str(args.max_workers),
    ]
    print(" ".join(shlex.quote(part) for part in cmd))
    if args.run:
        subprocess.run(cmd, check=True)


if __name__ == "__main__":
    main()
